// src/staticVideos.js
// Plain JavaScript conversion of your TypeScript data file.
// Exports: staticVideos, sampleVideos, getStaticVideosByCategory, allStaticVideos

// Helper: parse duration string "H:MM:SS" or "MM:SS" into seconds
function parseDurationToSeconds(duration) {
  if (!duration) return 0;
  const s = String(duration).trim();
  const parts = s.split(':').map((p) => p.replace(/\D/g, ''));
  if (parts.length === 1) {
    return parseInt(parts[0] || '0', 10) || 0;
  } else if (parts.length === 2) {
    const minutes = parseInt(parts[0] || '0', 10) || 0;
    const seconds = parseInt(parts[1] || '0', 10) || 0;
    return minutes * 60 + seconds;
  } else {
    const hours = parseInt(parts[0] || '0', 10) || 0;
    const minutes = parseInt(parts[1] || '0', 10) || 0;
    const seconds = parseInt(parts[2] || '0', 10) || 0;
    return hours * 3600 + minutes * 60 + seconds;
  }
}

// Helper: convert human-readable views like "2.4M" or "1,200" or "33.3K" into number
function parseViewsToNumber(views) {
  if (!views) return 0;
  let s = String(views).toLowerCase().replace(/views?/g, '').trim();
  s = s.replace(/,/g, '');
  const match = s.match(/^([\d.,]+)\s*([km])?$/i);
  if (!match) {
    const digits = s.match(/[\d]+/g);
    return digits ? parseInt(digits.join(''), 10) : 0;
  }
  const num = parseFloat(match[1].replace(/,/g, ''));
  const suffix = match[2] ? match[2].toLowerCase() : null;
  if (!suffix) return Math.round(num);
  if (suffix === 'k') return Math.round(num * 1000);
  if (suffix === 'm') return Math.round(num * 1000 * 1000);
  return Math.round(num);
}

// Helper: parse an uploadDate string into a timestamp (best-effort)
function parseUploadDateToTimestamp(uploadDate) {
  if (!uploadDate) return undefined;
  const relativeKeywords = ['ago', 'day', 'days', 'week', 'weeks', 'month', 'months', 'year', 'years'];
  if (relativeKeywords.some((k) => String(uploadDate).toLowerCase().includes(k))) return undefined;

  const parsed = Date.parse(uploadDate);
  if (!Number.isNaN(parsed)) return parsed;

  try {
    return Number(new Date(uploadDate));
  } catch {
    return undefined;
  }
}

// Normalizer: ensures numeric fields exist for future sorting/filtering
function makeVideo(v) {
  const durationSeconds = parseDurationToSeconds(v.duration);
  const viewsCount = parseViewsToNumber(v.views);
  const uploadTimestamp = parseUploadDateToTimestamp(v.uploadDate);
  return {
    ...v,
    durationSeconds,
    viewsCount,
    uploadTimestamp,
  };
}

// -------------------- staticVideos --------------------
// Static videos that always show first in each category
export const staticVideos = [
  makeVideo({
    id: "static-1",
    title: "How to Build a Gaming PC in 2025 (Ultimate Step-by-Step Guide)",
    thumbnail: "https://img.youtube.com/vi/FRhHZ5N4fPQ/hqdefault.jpg",
    duration: "46:41",
    views: "33.3K views",
    channelName: "Robeytech",
    uploadDate: "Apr 25, 2025",
    youtubeId: "FRhHZ5N4fPQ",
    category: "builds",
    isStatic: true,
  }),
  makeVideo({
    id: "static-2",
    title: "How to Build a PC! Step-by-step",
    thumbnail: "https://img.youtube.com/vi/IhX0fOUYd8Q/hqdefault.jpg",
    duration: "55:19",
    views: "12M views",
    channelName: "Bitwit",
    uploadDate: "May 24, 2017",
    youtubeId: "IhX0fOUYd8Q",
    category: "builds",
    isStatic: true,
  }),
  makeVideo({
    id: "static-3",
    title: "The $1000 Gaming PC Everyone Should Build in 2025",
    thumbnail: "https://img.youtube.com/vi/ULx3wX_E76Q/hqdefault.jpg",
    duration: "32:00",
    views: "56.9K views",
    channelName: "PC Builder",
    uploadDate: "Sep 13, 2025",
    youtubeId: "ULx3wX_E76Q",
    category: "builds",
    isStatic: true,
  }),
  makeVideo({
    id: "static-4",
    title: "Build the Best $600 Gaming PC - 2025",
    thumbnail: "https://img.youtube.com/vi/8j7BROw-DA4/hqdefault.jpg",
    duration: "14:00",
    views: "4.1M views",
    channelName: "Crater HQ",
    uploadDate: "Oct 2, 2024",
    youtubeId: "8j7BROw-DA4",
    category: "budget",
    isStatic: true,
  }),
  makeVideo({
    id: "static-5",
    title: "High-End Gaming PC: Premium Component Selection",
    thumbnail: "https://img.youtube.com/vi/v7MYOpFONCU/hqdefault.jpg",
    duration: "28:30",
    views: "2.7M views",
    channelName: "Premium PC",
    uploadDate: "Aug 15, 2024",
    youtubeId: "v7MYOpFONCU",
    category: "budget",
    isStatic: true,
  }),
];

// -------------------- sampleVideos --------------------
export const sampleVideos = [
  // 1
  makeVideo({
    id: "1",
    title: "Air Vs Liquid Cooling: Which is Best For YOUR PC? CPU Coolers Explained.",
    youtubeId: "kQSy8CS-iEI",
    thumbnail: "https://img.youtube.com/vi/kQSy8CS-iEI/hqdefault.jpg",
    duration: "17:54",
    views: "724K views",
    channelName: "Mr Matt Lee",
    uploadDate: "Nov 11, 2024",
    category: "news",
  }),
  makeVideo({
    id: "2",
    title: "How To Build a Gaming PC in 2025 - Step-By-Step Tutorial",
    youtubeId: "KEnOejQqAC8",
    thumbnail: "https://img.youtube.com/vi/KEnOejQqAC8/hqdefault.jpg",
    duration: "34:11",
    views: "2.4M views",
    channelName: "Paul's Hardware",
    uploadDate: "Jul 15, 2024",
    category: "builds",
  }),
  makeVideo({
    id: "3",
    title: "How to Build a PC - Step by Step Beginners Guide",
    youtubeId: "cMSj8DgnmaQ",
    thumbnail: "https://img.youtube.com/vi/cMSj8DgnmaQ/hqdefault.jpg",
    duration: "52:20",
    views: "2.8M views",
    channelName: "PC Builder",
    uploadDate: "Dec 29, 2021",
    category: "builds",
  }),
  makeVideo({
    id: "4",
    title: "The $1000 Gaming PC Everyone Should Build in 2025",
    youtubeId: "ULx3wX_E76Q",
    thumbnail: "https://img.youtube.com/vi/ULx3wX_E76Q/hqdefault.jpg",
    duration: "21:52",
    views: "56.9K views",
    channelName: "PC Builder",
    uploadDate: "Sep 13, 2025",
    category: "builds",
  }),
  makeVideo({
    id: "5",
    title: "Ultra Budget Gaming PC Build Challenge - AMD & Intel Edition",
    youtubeId: "r_m2oOOKazU",
    thumbnail: "https://img.youtube.com/vi/r_m2oOOKazU/hqdefault.jpg",
    duration: "31:48",
    views: "338K views",
    channelName: "Toasty Bros",
    uploadDate: "Jun 7, 2025",
    category: "builds",
  }),
  makeVideo({
    id: "6",
    title: "The Ultimate Guide to Building the Best Gaming PC in 2025",
    youtubeId: "foKVpNl2euA",
    thumbnail: "https://img.youtube.com/vi/foKVpNl2euA/hqdefault.jpg",
    duration: "36:14",
    views: "380K views",
    channelName: "RandomGaminginHD",
    uploadDate: "Sep 12, 2024",
    category: "builds",
  }),
  makeVideo({
    id: "7",
    title: "How To Build A Gaming PC - Complete Step By Step Guide",
    youtubeId: "FAYSsm43-5Y",
    thumbnail: "https://img.youtube.com/vi/FAYSsm43-5Y/hqdefault.jpg",
    duration: "45:12",
    views: "1.1M views",
    channelName: "The Don Tech",
    uploadDate: "Jan 20, 2024",
    category: "builds",
  }),
  makeVideo({
    id: "8",
    title: "How to build a PC — the last guide you'll ever need!",
    youtubeId: "BL4DCEp7blY",
    thumbnail: "https://img.youtube.com/vi/BL4DCEp7blY/hqdefault.jpg",
    duration: "1:42:00",
    views: "4.8M views",
    channelName: "Linus Tech Tips",
    uploadDate: "Apr 11, 2024",
    category: "builds",
  }),
  makeVideo({
    id: "9",
    title: "How to Build a PC - Full Detailed Build Guide (2025)",
    youtubeId: "Mho0M1Ns0Rw",
    thumbnail: "https://img.youtube.com/vi/Mho0M1Ns0Rw/hqdefault.jpg",
    duration: "2:13:02",
    views: "405K views",
    channelName: "Gamers Nexus",
    uploadDate: "Oct 3, 2024",
    category: "builds",
  }),
  makeVideo({
    id: "10",
    title: "How to build a Gaming PC",
    youtubeId: "gHAelSOF6f0",
    thumbnail: "https://img.youtube.com/vi/gHAelSOF6f0/hqdefault.jpg",
    duration: "30:42",
    views: "1.2M views",
    channelName: "JayzTwoCents",
    uploadDate: "May 16, 2017",
    category: "builds",
  }),
  makeVideo({
    id: "11",
    title: "How to install RAM: step by step guide",
    youtubeId: "AYZYxajdTdQ",
    thumbnail: "https://img.youtube.com/vi/AYZYxajdTdQ/hqdefault.jpg",
    duration: "10:30",
    views: "233K views",
    channelName: "PC Gamer",
    uploadDate: "Apr 2, 2024",
    category: "installing",
  }),
  makeVideo({
    id: "12",
    title: "Step-by-Step Guide to Installing ASUS Motherboards and PC",
    youtubeId: "6V3If3NpBHM",
    thumbnail: "https://img.youtube.com/vi/6V3If3NpBHM/hqdefault.jpg",
    duration: "8:50",
    views: "50K views",
    channelName: "ASUS",
    uploadDate: "Sep 2, 2024",
    category: "installing",
  }),
  makeVideo({
    id: "13",
    title: "HOW TO Install Motherboard, CPU, RAM, Video Card",
    youtubeId: "24rRBayvwqU",
    thumbnail: "https://img.youtube.com/vi/24rRBayvwqU/hqdefault.jpg",
    duration: "14:15",
    views: "620K views",
    channelName: "MSI Tech",
    uploadDate: "May 3, 2024",
    category: "installing",
  }),
  makeVideo({
    id: "14",
    title: "Best CPU Coolers: Air vs Liquid Cooling",
    youtubeId: "7VzXHUTqE7E",
    thumbnail: "https://img.youtube.com/vi/7VzXHUTqE7E/hqdefault.jpg",
    duration: "14:20",
    views: "78K views",
    channelName: "Cool Components",
    uploadDate: "Apr 25, 2024",
    category: "installing",
  }),
  makeVideo({
    id: "15",
    title: "Build a budget PC for office or school!",
    youtubeId: "sYMoYjWlDVQ",
    thumbnail: "https://img.youtube.com/vi/sYMoYjWlDVQ/hqdefault.jpg",
    duration: "13:15",
    views: "1.2K views",
    channelName: "TEAMGROUP",
    uploadDate: "Mar 31, 2022",
    category: "installing",
  }),
  makeVideo({
    id: "16",
    title: "SSD vs HDD: Storage Performance Comparison",
    youtubeId: "YQEjGKYXjw8",
    thumbnail: "https://img.youtube.com/vi/YQEjGKYXjw8/hqdefault.jpg",
    duration: "13:20",
    views: "500K views",
    channelName: "Storage Solutions",
    uploadDate: "Sep 20, 2023",
    category: "installing",
  }),
  makeVideo({
    id: "17",
    title: "How To Build A Gaming PC in 2025 - Step-By-Step Guide!",
    youtubeId: "AJtfMrwmtZU",
    thumbnail: "https://img.youtube.com/vi/AJtfMrwmtZU/hqdefault.jpg",
    duration: "44:13",
    views: "1.3M views",
    channelName: "Paul's Hardware",
    uploadDate: "Apr 17, 2024",
    category: "builds",
  }),
  makeVideo({
    id: "18",
    title: "What to Do If Your PC Build WON'T Boot! Full Guide",
    youtubeId: "razvo7uWYA0",
    thumbnail: "https://img.youtube.com/vi/razvo7uWYA0/hqdefault.jpg",
    duration: "11:55",
    views: "35K views",
    channelName: "TechteamGB",
    uploadDate: "Sep 21, 2024",
    category: "troubleshooting",
  }),
  makeVideo({
    id: "19",
    title: "How to Fix Blue Screen Error on Windows 10/11",
    youtubeId: "DOQ-5fVm2BI",
    thumbnail: "https://img.youtube.com/vi/DOQ-5fVm2BI/hqdefault.jpg",
    duration: "14:40",
    views: "400K views",
    channelName: "ByteGeek",
    uploadDate: "May 23, 2024",
    category: "troubleshooting",
  }),
  makeVideo({
    id: "20",
    title: "How to Fix Windows Not Booting: Blue Screen Repair",
    youtubeId: "7Syyhc3Hr8w",
    thumbnail: "https://img.youtube.com/vi/7Syyhc3Hr8w/hqdefault.jpg",
    duration: "16:05",
    views: "340K views",
    channelName: "Felper's Technology",
    uploadDate: "Apr 11, 2024",
    category: "troubleshooting",
  }),
  makeVideo({
    id: "21",
    title: "Build the Best $600 Gaming PC - 2025",
    youtubeId: "8j7BROw-DA4",
    thumbnail: "https://img.youtube.com/vi/8j7BROw-DA4/hqdefault.jpg",
    duration: "14:00",
    views: "15K views",
    channelName: "Crater HQ",
    uploadDate: "Oct 2, 2024",
    category: "budget",
  }),
  makeVideo({
    id: "22",
    title: "BEST $600 Budget Gaming PC Build Guide for 2025",
    youtubeId: "LWLNYDK88J0",
    thumbnail: "https://img.youtube.com/vi/LWLNYDK88J0/hqdefault.jpg",
    duration: "20:45",
    views: "55K views",
    channelName: "ScatterVolt",
    uploadDate: "Sep 19, 2024",
    category: "budget",
  }),
  makeVideo({
    id: "23",
    title: "$600 Budget Gaming PC With ALL NEW Parts - Full Build Guide",
    youtubeId: "u1MeYFuduLo",
    thumbnail: "https://img.youtube.com/vi/u1MeYFuduLo/hqdefault.jpg",
    duration: "16:30",
    views: "25K views",
    channelName: "PC Bros",
    uploadDate: "Sep 28, 2024",
    category: "budget",
  }),
  makeVideo({
    id: "24",
    title: "The BEST $800 Gaming PC Build Guide (2025)",
    youtubeId: "gPKC-JmMg4g",
    thumbnail: "https://img.youtube.com/vi/gPKC-JmMg4g/hqdefault.jpg",
    duration: "10:15",
    views: "15K views",
    channelName: "Killswitch PCs",
    uploadDate: "Sep 13, 2024",
    category: "budget",
  }),
  makeVideo({
    id: "25",
    title: "Intel's New GPU: Xe3 Architecture Changes, Handheld Gaming CPUs, & XeSS3",
    youtubeId: "HwZx9RIl13Y",
    thumbnail: "https://img.youtube.com/vi/HwZx9RIl13Y/hqdefault.jpg",
    duration: "27:40",
    views: "20K views",
    channelName: "Gamers Nexus",
    uploadDate: "Oct 3, 2024",
    category: "news",
  }),
  makeVideo({
    id: "26",
    title: "First Person View PC Build Guide! (POV)",
    youtubeId: "v7MYOpFONCU",
    thumbnail: "https://img.youtube.com/vi/v7MYOpFONCU/hqdefault.jpg",
    duration: "28:30",
    views: "12M views",
    channelName: "Linus Tech Tips",
    uploadDate: "Dec 31, 2019",
    category: "builds",
  }),
  makeVideo({
    id: "27",
    title: "The Best GPU & CPU Combos RIGHT NOW For PC Gaming!",
    youtubeId: "UHm5wTQBFlI",
    thumbnail: "https://img.youtube.com/vi/UHm5wTQBFlI/hqdefault.jpg",
    duration: "14:50",
    views: "130K views",
    channelName: "PC Centric",
    uploadDate: "Aug 22, 2024",
    category: "compatibility",
  }),
  makeVideo({
    id: "28",
    title: "STOP Buying Bad Combos! Best CPU and GPU Combo 2025",
    youtubeId: "EhcNjFlc8ok",
    thumbnail: "https://img.youtube.com/vi/EhcNjFlc8ok/hqdefault.jpg",
    duration: "12:00",
    views: "60K views",
    channelName: "Greg Salazar",
    uploadDate: "Sep 13, 2024",
    category: "compatibility",
  }),
  makeVideo({
    id: "29",
    title: "How to Pick the Right PC Parts in 2025!",
    youtubeId: "gcy-Q99gvw8",
    thumbnail: "https://img.youtube.com/vi/gcy-Q99gvw8/hqdefault.jpg",
    duration: "9:30",
    views: "50K views",
    channelName: "TechteamGB",
    uploadDate: "Sep 19, 2024",
    category: "compatibility",
  }),
  makeVideo({
    id: "30",
    title: "Best PC Build 2025: PC Parts Explained",
    youtubeId: "sLB2G9p72r8",
    thumbnail: "https://img.youtube.com/vi/sLB2G9p72r8/hqdefault.jpg",
    duration: "11:45",
    views: "100K views",
    channelName: "Paul's Hardware",
    uploadDate: "Aug 1, 2024",
    category: "compatibility",
  }),
  makeVideo({
    id: "31",
    title: "Intel vs AMD: CPU Comparison Guide 2024",
    youtubeId: "PSxuiWih_Z8",
    thumbnail: "https://img.youtube.com/vi/PSxuiWih_Z8/hqdefault.jpg",
    duration: "18:30",
    views: "10K views",
    channelName: "Tech Specs",
    uploadDate: "Oct 2, 2024",
    category: "compatibility",
  }),
  makeVideo({
    id: "32",
    title: "The BEST Gaming PC Build Under $1000 - Summer 2025",
    youtubeId: "-1dtLswCms8",
    thumbnail: "https://img.youtube.com/vi/-1dtLswCms8/hqdefault.jpg",
    duration: "17:15",
    views: "230K views",
    channelName: "Paul's Hardware",
    uploadDate: "Jul 15, 2024",
    category: "builds",
  }),
  makeVideo({
    id: "33",
    title: "Power Supply Calculator: How Much Wattage Do You Need?",
    youtubeId: "bUh2EZzJZRU",
    thumbnail: "https://img.youtube.com/vi/bUh2EZzJZRU/hqdefault.jpg",
    duration: "10:30",
    views: "90K views",
    channelName: "PSU Master",
    uploadDate: "Mar 20, 2024",
    category: "compatibility",
  }),
  makeVideo({
    id: "34",
    title: "PC Build Timelapse 2024: Ryzen 5 & RTX 4060",
    youtubeId: "xN1i0Y2Qy5I",
    thumbnail: "https://img.youtube.com/vi/xN1i0Y2Qy5I/hqdefault.jpg",
    duration: "8:55",
    views: "150K views",
    channelName: "Builds & Co.",
    uploadDate: "Aug 10, 2024",
    category: "builds",
  }),
  makeVideo({
    id: "35",
    title: "A Beginner's Guide to PC Part Selection",
    youtubeId: "cg6HmFAQ314",
    thumbnail: "https://img.youtube.com/vi/cg6HmFAQ314/hqdefault.jpg",
    duration: "12:30",
    views: "80K views",
    channelName: "Tech Explained",
    uploadDate: "Jul 25, 2024",
    category: "compatibility",
  }),
  makeVideo({
    id: "36",
    title: "Troubleshooting: How to Fix a Freezing PC",
    youtubeId: "EMOIXqjIJCc",
    thumbnail: "https://img.youtube.com/vi/EMOIXqjIJCc/hqdefault.jpg",
    duration: "11:20",
    views: "25K views",
    channelName: "PC Repair Guru",
    uploadDate: "Jun 15, 2024",
    category: "troubleshooting",
  }),
  makeVideo({
    id: "37",
    title: "Install Windows 11 on Your New PC (Step-by-Step)",
    youtubeId: "wrX1ZTi_Nug",
    thumbnail: "https://img.youtube.com/vi/wrX1ZTi_Nug/hqdefault.jpg",
    duration: "15:00",
    views: "450K views",
    channelName: "OS Guides",
    uploadDate: "Mar 1, 2024",
    category: "installing",
  }),
  makeVideo({
    id: "38",
    title: "Do You REALLY Need an Expensive Motherboard?",
    youtubeId: "isjZJsLCaV4",
    thumbnail: "https://img.youtube.com/vi/isjZJsLCaV4/hqdefault.jpg",
    duration: "18:40",
    views: "1.2M views",
    channelName: "Hardware Secrets",
    uploadDate: "Jan 10, 2024",
    category: "compatibility",
  }),
  makeVideo({
    id: "39",
    title: "The Ultimate Cable Management Guide for PC Builders",
    youtubeId: "TS7NiGMpbrY",
    thumbnail: "https://img.youtube.com/vi/TS7NiGMpbrY/hqdefault.jpg",
    duration: "21:10",
    views: "320K views",
    channelName: "Aesthetic Builds",
    uploadDate: "May 20, 2024",
    category: "installing",
  }),
  makeVideo({
    id: "40",
    title: "Testing the Cheapest $300 Gaming PC from eBay",
    youtubeId: "6X6CJpoRtsw",
    thumbnail: "https://img.youtube.com/vi/6X6CJpoRtsw/hqdefault.jpg",
    duration: "24:50",
    views: "980K views",
    channelName: "Budget Gamer",
    uploadDate: "Feb 1, 2024",
    category: "budget",
  }),
  makeVideo({
    id: "41",
    title: "PC News: New AMD Ryzen 9000 Series Announcement",
    youtubeId: "NRnnnhCVjp0",
    thumbnail: "https://img.youtube.com/vi/NRnnnhCVjp0/hqdefault.jpg",
    duration: "14:30",
    views: "45K views",
    channelName: "Tech Brief",
    uploadDate: "Dec 10, 2024",
    category: "news",
  }),
  makeVideo({
    id: "42",
    title: "How to Build a Mini-ITX SFF Gaming PC",
    youtubeId: "bz2SYkDBtbs",
    thumbnail: "https://img.youtube.com/vi/bz2SYkDBtbs/hqdefault.jpg",
    duration: "28:05",
    views: "210K views",
    channelName: "Small Form Factor",
    uploadDate: "Sep 5, 2024",
    category: "builds",
  }),
  makeVideo({
    id: "43",
    title: "Fixing Slow Startup Times in Windows 10/11",
    youtubeId: "ExOPdpnjpQk",
    thumbnail: "https://img.youtube.com/vi/ExOPdpnjpQk/hqdefault.jpg",
    duration: "8:25",
    views: "180K views",
    channelName: "IT Support",
    uploadDate: "Apr 20, 2024",
    category: "troubleshooting",
  }),
  makeVideo({
    id: "44",
    title: "Budget-Friendly RAM: Speed vs. Latency Explained",
    youtubeId: "Mmq_fASrTB4",
    thumbnail: "https://img.youtube.com/vi/Mmq_fASrTB4/hqdefault.jpg",
    duration: "13:45",
    views: "60K views",
    channelName: "Memory Masters",
    uploadDate: "Oct 1, 2024",
    category: "budget",
  }),
  makeVideo({
    id: "45",
    title: "Motherboard BIOS Updates: When and How to Do It",
    youtubeId: "7SjQo7wrWq4",
    thumbnail: "https://img.youtube.com/vi/7SjQo7wrWq4/hqdefault.jpg",
    duration: "16:00",
    views: "95K views",
    channelName: "Flashpoint Tech",
    uploadDate: "Mar 25, 2024",
    category: "installing",
  }),
  makeVideo({
    id: "46",
    title: "20 Essential PC Maintenance Tips for Longevity",
    youtubeId: "7t9S_Ymwo4A",
    thumbnail: "https://img.youtube.com/vi/7t9S_Ymwo4A/hqdefault.jpg",
    duration: "10:50",
    views: "50K views",
    channelName: "PC Health",
    uploadDate: "Sep 1, 2024",
    category: "troubleshooting",
  }),
  makeVideo({
    id: "47",
    title: "The State of RGB in 2025: Too Much or Just Right?",
    youtubeId: "NwuSXgiGVpo",
    thumbnail: "https://img.youtube.com/vi/NwuSXgiGVpo/hqdefault.jpg",
    duration: "17:00",
    views: "40K views",
    channelName: "PC Aesthetics",
    uploadDate: "Oct 15, 2024",
    category: "news",
  }),
  makeVideo({
    id: "48",
    title: "How to Choose the Right PC Case Size (ATX, Micro-ATX, Mini-ITX)",
    youtubeId: "gdPnsuo8AVw",
    thumbnail: "https://img.youtube.com/vi/gdPnsuo8AVw/hqdefault.jpg",
    duration: "9:15",
    views: "75K views",
    channelName: "Case King",
    uploadDate: "May 10, 2024",
    category: "compatibility",
  }),
  makeVideo({
    id: "49",
    title: "Laptops vs. Desktops: Which is Right for You in 2025?",
    youtubeId: "FGDRn-AQmHU",
    thumbnail: "https://img.youtube.com/vi/FGDRn-AQmHU/hqdefault.jpg",
    duration: "15:10",
    views: "110K views",
    channelName: "Mobile Tech",
    uploadDate: "Apr 5, 2024",
    category: "news",
  }),
  makeVideo({
    id: "50",
    title: "The Easiest Way to Remove & Replace a CPU",
    youtubeId: "A24Rv3PBeuA",
    thumbnail: "https://img.youtube.com/vi/A24Rv3PBeuA/hqdefault.jpg",
    duration: "10:15",
    views: "600K views",
    channelName: "PC Mechanics",
    uploadDate: "Aug 1, 2023",
    category: "installing",
  }),
  makeVideo({
    id: "51",
    title: "How to Build an Ultra High-End PC: Part 1 - Component Selection",
    youtubeId: "f4iSkGqx_Ng",
    thumbnail: "https://img.youtube.com/vi/f4iSkGqx_Ng/hqdefault.jpg",
    duration: "35:45",
    views: "2.1M views",
    channelName: "Extreme Gaming",
    uploadDate: "Feb 20, 2025",
    category: "builds",
  }),
  makeVideo({
    id: "52",
    title: "Troubleshooting: POST Codes and What They Mean",
    youtubeId: "Xem2GQxljtk",
    thumbnail: "https://img.youtube.com/vi/Xem2GQxljtk/hqdefault.jpg",
    duration: "14:10",
    views: "75K views",
    channelName: "The BIOS Guy",
    uploadDate: "Sep 22, 2024",
    category: "troubleshooting",
  }),
  makeVideo({
    id: "53",
    title: "Is It Worth Buying a Used GPU in 2025?",
    youtubeId: "7FPsLYIbBxg",
    thumbnail: "https://img.youtube.com/vi/7FPsLYIbBxg/hqdefault.jpg",
    duration: "17:30",
    views: "140K views",
    channelName: "Second-Hand Tech",
    uploadDate: "Oct 5, 2024",
    category: "budget",
  }),
  makeVideo({
    id: "54",
    title: "How to Install an Operating System on a New SSD",
    youtubeId: "_TNqR9lIZxs",
    thumbnail: "https://img.youtube.com/vi/_TNqR9lIZxs/hqdefault.jpg",
    duration: "10:45",
    views: "90K views",
    channelName: "Storage Guy",
    uploadDate: "Aug 20, 2024",
    category: "installing",
  }),
  makeVideo({
    id: "55",
    title: "Best Value Gaming Monitor for PC in 2025",
    youtubeId: "Agw4wFuVS7M",
    thumbnail: "https://img.youtube.com/vi/Agw4wFuVS7M/hqdefault.jpg",
    duration: "14:20",
    views: "60K views",
    channelName: "Display Review",
    uploadDate: "Sep 15, 2024",
    category: "news",
  }),
  makeVideo({
    id: "56",
    title: "The Ultimate Guide to CPU Overclocking for Beginners",
    youtubeId: "g5JuLf-t5hA",
    thumbnail: "https://img.youtube.com/vi/g5JuLf-t5hA/hqdefault.jpg",
    duration: "25:30",
    views: "190K views",
    channelName: "Overclock Central",
    uploadDate: "Jun 1, 2024",
    category: "compatibility",
  }),
  makeVideo({
    id: "57",
    title: "PC Build Checklist: Did You Forget Anything?",
    youtubeId: "I46CV8lSmjg",
    thumbnail: "https://img.youtube.com/vi/I46CV8lSmjg/hqdefault.jpg",
    duration: "7:50",
    views: "45K views",
    channelName: "PC Guide",
    uploadDate: "Jul 1, 2024",
    category: "builds",
  }),
  makeVideo({
    id: "58",
    title: "Diagnosing Graphics Card Problems: Artifacts and Crashes",
    youtubeId: "r3Jy5dHOj3g",
    thumbnail: "https://img.youtube.com/vi/r3Jy5dHOj3g/hqdefault.jpg",
    duration: "13:10",
    views: "110K views",
    channelName: "GPU Doctor",
    uploadDate: "May 25, 2024",
    category: "troubleshooting",
  }),
  makeVideo({
    id: "59",
    title: "Can You Build a Good PC with Refurbished Parts?",
    youtubeId: "Iom5xxdv934",
    thumbnail: "https://img.youtube.com/vi/Iom5xxdv934/hqdefault.jpg",
    duration: "20:00",
    views: "85K views",
    channelName: "Used Tech",
    uploadDate: "Apr 10, 2024",
    category: "budget",
  }),
  makeVideo({
    id: "60",
    title: "Installing M.2 SSDs: The Complete Guide",
    youtubeId: "nu1hNTyPANA",
    thumbnail: "https://img.youtube.com/vi/nu1hNTyPANA/hqdefault.jpg",
    duration: "11:05",
    views: "130K views",
    channelName: "Storage Solutions",
    uploadDate: "Mar 15, 2024",
    category: "installing",
  }),
  makeVideo({
    id: "61",
    title: "Tech News Roundup: Latest from CES 2025",
    youtubeId: "mV1qRMLCNE4",
    thumbnail: "https://img.youtube.com/vi/mV1qRMLCNE4/hqdefault.jpg",
    duration: "22:40",
    views: "70K views",
    channelName: "Future Tech",
    uploadDate: "Jan 8, 2025",
    category: "news",
  }),
  makeVideo({
    id: "62",
    title: "Ray Tracing vs. Rasterization: Visual Comparison",
    youtubeId: "O581KArEESM",
    thumbnail: "https://img.youtube.com/vi/O581KArEESM/hqdefault.jpg",
    duration: "16:20",
    views: "300K views",
    channelName: "Graphics Analyst",
    uploadDate: "Feb 14, 2024",
    category: "compatibility",
  }),
  makeVideo({
    id: "63",
    title: "How to Build a YouTube Channel (For Beginners)",
    youtubeId: "6ZoMpaU3gzc",
    thumbnail: "https://img.youtube.com/vi/6ZoMpaU3gzc/hqdefault.jpg",
    duration: "6:54",
    views: "75K views",
    channelName: "Karl Bro",
    uploadDate: "Jan 25, 2025",
    category: "news",
  }),
  makeVideo({
    id: "64",
    title: "Understanding PCIe Lanes and Bandwidth",
    youtubeId: "Ii7sxxAB2Dk",
    thumbnail: "https://img.youtube.com/vi/Ii7sxxAB2Dk/hqdefault.jpg",
    duration: "10:10",
    views: "150K views",
    channelName: "Hardware Class",
    uploadDate: "Nov 1, 2023",
    category: "compatibility",
  }),
  makeVideo({
    id: "65",
    title: "YouTube Analytics: My Beginner's Guide",
    youtubeId: "Lnzhqfo_ZAE",
    thumbnail: "https://img.youtube.com/vi/Lnzhqfo_ZAE/hqdefault.jpg",
    duration: "12:15",
    views: "50K views",
    channelName: "Creator IQ",
    uploadDate: "May 13, 2025",
    category: "news",
  }),
  makeVideo({
    id: "66",
    title: "How to Build an ENTRY-LEVEL Gaming PC (Under $500)",
    youtubeId: "VkFPMh3F7NI",
    thumbnail: "https://img.youtube.com/vi/VkFPMh3F7NI/hqdefault.jpg",
    duration: "25:00",
    views: "1.5M views",
    channelName: "Cheap Gamer",
    uploadDate: "Dec 1, 2024",
    category: "budget",
  }),
  makeVideo({
    id: "67",
    title: "Beginner PC Build Guide: What You NEED to Know",
    youtubeId: "Y2OSuzdhyAo",
    thumbnail: "https://img.youtube.com/vi/Y2OSuzdhyAo/hqdefault.jpg",
    duration: "40:00",
    views: "900K views",
    channelName: "New Builder",
    uploadDate: "Oct 20, 2024",
    category: "builds",
  }),
  makeVideo({
    id: "68",
    title: "My PC Won't Turn On! - Diagnostics and Fixes",
    youtubeId: "fh6uyltADMs",
    thumbnail: "https://img.youtube.com/vi/fh6uyltADMs/hqdefault.jpg",
    duration: "16:45",
    views: "250K views",
    channelName: "The Fixer",
    uploadDate: "Jul 20, 2024",
    category: "troubleshooting",
  }),
  makeVideo({
    id: "69",
    title: "Best CPU For Gaming in 2025: Intel vs. AMD Showdown",
    youtubeId: "E9IxUCI3A-w",
    thumbnail: "https://img.youtube.com/vi/E9IxUCI3A-w/hqdefault.jpg",
    duration: "19:00",
    views: "160K views",
    channelName: "Processor Pro",
    uploadDate: "Jan 1, 2025",
    category: "compatibility",
  }),
  makeVideo({
    id: "70",
    title: "How to Check Who Subscribed to your YouTube Channel",
    youtubeId: "Qh-uXdFQC1c",
    thumbnail: "https://img.youtube.com/vi/Qh-uXdFQC1c/hqdefault.jpg",
    duration: "6:54",
    views: "75K views",
    channelName: "Karl Bro",
    uploadDate: "Jan 25, 2025",
    category: "news",
  }),
  makeVideo({
    id: "71",
    title: "YouTube Search Insights: Inside the New Research Tab",
    youtubeId: "TNPFqsRqUC8",
    thumbnail: "https://img.youtube.com/vi/TNPFqsRqUC8/hqdefault.jpg",
    duration: "8:50",
    views: "50K views",
    channelName: "Creator Insider",
    uploadDate: "Oct 7, 2022",
    category: "news",
  }),
  makeVideo({
    id: "72",
    title: "PC Parts Explained: Motherboards, RAM, and More",
    youtubeId: "sLB2G9p72r8",
    thumbnail: "https://img.youtube.com/vi/sLB2G9p72r8/hqdefault.jpg",
    duration: "11:45",
    views: "100K views",
    channelName: "Paul's Hardware",
    uploadDate: "Aug 1, 2024",
    category: "compatibility",
  }),
  makeVideo({
    id: "73",
    title: "Installing Drivers on a New PC Build: The Easy Way",
    youtubeId: "WpnLehvOM6E",
    thumbnail: "https://img.youtube.com/vi/WpnLehvOM6E/hqdefault.jpg",
    duration: "10:20",
    views: "70K views",
    channelName: "Driver Master",
    uploadDate: "Oct 1, 2024",
    category: "installing",
  }),
  makeVideo({
    id: "74",
    title: "How to Clean Dust from Your PC Safely",
    youtubeId: "iN2HqCpdOzE",
    thumbnail: "https://img.youtube.com/vi/iN2HqCpdOzE/hqdefault.jpg",
    duration: "9:40",
    views: "150K views",
    channelName: "PC Care",
    uploadDate: "May 1, 2024",
    category: "troubleshooting",
  }),
  makeVideo({
    id: "75",
    title: "How to choose the right PC parts... (Advanced)",
    youtubeId: "BQ308X5_xn4",
    thumbnail: "https://img.youtube.com/vi/BQ308X5_xn4/hqdefault.jpg",
    duration: "18:52",
    views: "700K views",
    channelName: "JayzTwoCents",
    uploadDate: "Oct 23, 2022",
    category: "compatibility",
  }),
];

// Helper function to get static videos by category
export function getStaticVideosByCategory(category) {
  if (!category || String(category).toLowerCase() === "all") {
    return [...staticVideos, ...sampleVideos];
  }
  return [...staticVideos, ...sampleVideos].filter(
    (video) => (video.category || "").toLowerCase() === String(category).toLowerCase()
  );
}

// Optional: export all static data together if needed
export const allStaticVideos = [...staticVideos, ...sampleVideos];
export default allStaticVideos;
